services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
      - 9000:9000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - ./Back/.env  
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql  

  app:
    build: 
      context: ./Back  
      dockerfile: Dockerfile.Node
    container_name: node_app
    restart: always
    env_file:
      - ./Back/.env  
    ports:
      - "3002:3002"  
    depends_on:
      - mysql
    volumes:
      - ./Back:/app  
      - /app/node_modules  

  frontend:
    build: 
      context: ./Front/vuetify-boxhead  
      dockerfile: Dockerfile.Vuetify
    container_name: vuetify_frontend
    restart: always
    ports:
      - "7001:7001"  
    volumes:
      - ./Front/vuetify-boxhead:/app
      - /app/node_modules
    working_dir: /app
  
  python-app:
    build:
      context: ./Back/statistics
      dockerfile: Dockerfile.Python
    container_name: python_app
    restart: always
    env_file:
      - ./Back/.env
    volumes:
      - ./Back/statistics:/app
      - ./Back/statistics:/Images

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  apache:
    image: httpd:latest
    container_name: apache_server
    restart: always
    ports:
      - "7002:7002"
    volumes:
      - ./public_html:/usr/local/apache2/htdocs/

volumes:
  data:
  mysql_data:
