services:
  # Contenedor de MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - ./Back/.env  # <-- Carga las variables desde .env
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Contraseña para el root de MySQL
    ports:
      - "3306:3306"  # Mapea el puerto 3306 del contenedor al host
    volumes:
      - mysql_data:/var/lib/mysql  # Volumen para persistir datos

  # Contenedor de Node.js (Backend)
  app:
    build: 
      context: ./Back  # Se especifica la carpeta donde está el Dockerfile
      dockerfile: Dockerfile.Node
    container_name: node_app
    restart: always
    env_file:
      - ./Back/.env  # Carga las variables desde .env
    ports:
      - "3002:3002"  # Mapea el puerto 3001 del contenedor al host
    depends_on:
      - mysql  # Asegura que MySQL esté disponible antes de iniciar el app
    volumes:
      - ./Back:/app  # Mapea el código del backend al contenedor
      - /app/node_modules  # Volumen para preservar las dependencias

  # Contenedor de Vuetify (Frontend)
  frontend:
    build: 
      context: ./Front/vuetify-boxhead  # Ruta al Dockerfile de Vuetify
      dockerfile: Dockerfile.vuetify
    container_name: vuetify_frontend
    restart: always
    ports:
      - "7001:7001"  # Mapea el puerto 5170 del contenedor al host
    volumes:
      - ./Front/vuetify-boxhead:/app
      - /app/node_modules
    working_dir: /app
   
  # Contenedor de Adminer (Interfaz para gestionar la base de datos)
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"  # Adminer será accesible en http://localhost:8080

volumes:
  mysql_data: