# Usa una imagen base de Python
FROM python:3.9-slim

# Configura el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo requirements.txt dentro del contenedor
COPY requirements.txt .

# Instala las dependencias listadas en requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el código del proyecto al contenedor
COPY . .

# Comando para ejecutar tu script de Python (ajústalo según tu archivo principal)
CMD ["python3", "stats.py"]
